// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUaxudX3YZ5MOtsg3GFqBiYrdBaFlfYfM',
    appId: '1:473273471612:web:cc8c43ea217b3e4a482ff9',
    messagingSenderId: '473273471612',
    projectId: 'fluttter-twitter',
    authDomain: 'fluttter-twitter.firebaseapp.com',
    storageBucket: 'fluttter-twitter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD2z2uWDTA8U1V6DBXAafw1DQBnunY7DE',
    appId: '1:473273471612:android:7135afd044c3d261482ff9',
    messagingSenderId: '473273471612',
    projectId: 'fluttter-twitter',
    storageBucket: 'fluttter-twitter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChNz-zFtAkvWhIO0vVba2A1oVN6q82JZo',
    appId: '1:473273471612:ios:9e33bbfc11c1d2be482ff9',
    messagingSenderId: '473273471612',
    projectId: 'fluttter-twitter',
    storageBucket: 'fluttter-twitter.appspot.com',
    iosBundleId: 'com.simpleittools.flutterTwit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChNz-zFtAkvWhIO0vVba2A1oVN6q82JZo',
    appId: '1:473273471612:ios:e0978115ca264ce2482ff9',
    messagingSenderId: '473273471612',
    projectId: 'fluttter-twitter',
    storageBucket: 'fluttter-twitter.appspot.com',
    iosBundleId: 'com.simpleittools.flutterTwit.RunnerTests',
  );
}
